-- GRID OS initial schema. Apply through Supabase SQL editor or CLI migrations.
create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, name text not null default '', email text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspaces(id uuid primary key default gen_random_uuid(), name text not null, currency text not null default 'INR' check(currency='INR'), timezone text not null default 'Asia/Kolkata', billing_address text, tax_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspace_members(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, user_id uuid not null references public.profiles, role text not null check(role in ('Admin','Manager','Editor')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,user_id));
create table public.clients(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, name text not null, contact text, email text, phone text, billing_address text, tax_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id));
create table public.leads(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, name text not null, company text, email text, phone text, source text, service text, budget numeric(14,2) check(budget>=0), owner_id uuid, expected_date date, notes text, client_id uuid, status text not null default 'New' check(status in ('New','Contacted','Discussion','Proposal Sent','Won','Lost')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), foreign key(workspace_id,client_id) references public.clients(workspace_id,id), foreign key(workspace_id,owner_id) references public.workspace_members(workspace_id,user_id));
create sequence public.document_number_seq;
create table public.estimates(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, name text not null, number text not null default ('EST-'||lpad(nextval('public.document_number_seq')::text,5,'0')), client_id uuid not null, lead_id uuid, issue_date date not null, valid_until date not null, discount numeric(14,2) not null default 0 check(discount>=0), notes text, payment_terms text, terms text, status text not null default 'Draft' check(status in ('Draft','Sent','Accepted','Rejected','Expired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), unique(workspace_id,number), check(valid_until>=issue_date), foreign key(workspace_id,client_id) references public.clients(workspace_id,id), foreign key(workspace_id,lead_id) references public.leads(workspace_id,id));
create table public.projects(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, name text not null, client_id uuid not null, estimate_id uuid, lead_id uuid, project_type text, owner_id uuid, start_date date, deadline date, brief text, delivered_at timestamptz, status text not null default 'Planning' check(status in ('Planning','Pre-production','Shoot Scheduled','In Production','Editing','Client Review','Revisions','Ready for Delivery','Delivered','Completed','On Hold')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), unique(estimate_id), unique(lead_id), check(deadline is null or start_date is null or deadline>=start_date), foreign key(workspace_id,client_id) references public.clients(workspace_id,id), foreign key(workspace_id,estimate_id) references public.estimates(workspace_id,id), foreign key(workspace_id,lead_id) references public.leads(workspace_id,id), foreign key(workspace_id,owner_id) references public.workspace_members(workspace_id,user_id));
create table public.project_members(id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, user_id uuid not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,user_id), foreign key(workspace_id,project_id) references public.projects(workspace_id,id) on delete cascade, foreign key(workspace_id,user_id) references public.workspace_members(workspace_id,user_id));
create table public.shoots(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, project_id uuid not null, name text not null, date date not null, start_time time not null, end_time time, location text, shoot_type text, crew text, equipment text, shot_notes text, notes text, status text not null default 'Planned' check(status in ('Planned','Confirmed','Completed','Cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), check(end_time is null or end_time>start_time), foreign key(workspace_id,project_id) references public.projects(workspace_id,id));
create table public.deliverables(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, project_id uuid not null, name text not null, type text, assignee_id uuid, due_date date, revision_count integer default 0 check(revision_count>=0), delivery_url text, notes text, status text not null default 'Not Started' check(status in ('Not Started','In Progress','Internal Review','Client Review','Revision','Approved','Delivered')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), unique(workspace_id,project_id,id), foreign key(workspace_id,project_id) references public.projects(workspace_id,id), foreign key(workspace_id,assignee_id) references public.workspace_members(workspace_id,user_id));
create table public.tasks(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, project_id uuid not null, deliverable_id uuid, name text not null, assignee_id uuid, due_date date, priority text default 'Medium' check(priority in ('Low','Medium','High','Urgent')), notes text, status text not null default 'To Do' check(status in ('To Do','In Progress','Review','Done')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), foreign key(workspace_id,project_id) references public.projects(workspace_id,id), foreign key(workspace_id,project_id,deliverable_id) references public.deliverables(workspace_id,project_id,id), foreign key(workspace_id,assignee_id) references public.workspace_members(workspace_id,user_id));
create table public.invoices(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, name text not null, number text not null default ('INV-'||lpad(nextval('public.document_number_seq')::text,5,'0')), client_id uuid not null, project_id uuid not null, issue_date date not null, due_date date not null, discount numeric(14,2) not null default 0 check(discount>=0), notes text, payment_terms text, status text not null default 'Draft' check(status in ('Draft','Sent','Cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), unique(workspace_id,number), check(due_date>=issue_date), foreign key(workspace_id,client_id) references public.clients(workspace_id,id), foreign key(workspace_id,project_id) references public.projects(workspace_id,id));
create table public.estimate_items(id uuid primary key default gen_random_uuid(), workspace_id uuid not null, estimate_id uuid not null, service text not null, description text, quantity numeric(12,3) not null check(quantity>0), rate numeric(14,2) not null check(rate>=0), tax numeric(5,2) not null default 0 check(tax between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(workspace_id,estimate_id) references public.estimates(workspace_id,id) on delete cascade);
create table public.invoice_items(id uuid primary key default gen_random_uuid(), workspace_id uuid not null, invoice_id uuid not null, service text not null, description text, quantity numeric(12,3) not null check(quantity>0), rate numeric(14,2) not null check(rate>=0), tax numeric(5,2) not null default 0 check(tax between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(workspace_id,invoice_id) references public.invoices(workspace_id,id) on delete cascade);
create table public.payments(id uuid primary key default gen_random_uuid(), workspace_id uuid not null, invoice_id uuid not null, amount numeric(14,2) not null check(amount>0), date date not null, method text, reference text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(workspace_id,invoice_id) references public.invoices(workspace_id,id));
create table public.activity_logs(id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid, entity text not null, record_id uuid not null, action text not null, actor_id uuid references public.profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create function public.is_member(w uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from workspace_members where workspace_id=w and user_id=auth.uid()); $$;
create function public.is_manager(w uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from workspace_members where workspace_id=w and user_id=auth.uid() and role in ('Admin','Manager')); $$;
create function public.is_admin(w uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from workspace_members where workspace_id=w and user_id=auth.uid() and role='Admin'); $$;
create function public.can_project(w uuid,p uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_manager(w) or exists(select 1 from project_members where workspace_id=w and project_id=p and user_id=auth.uid()); $$;
create function public.touch_record() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','workspaces','workspace_members','clients','leads','estimates','projects','project_members','shoots','deliverables','tasks','invoices','estimate_items','invoice_items','payments','activity_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('create trigger touch before update on public.%I for each row execute function public.touch_record()',t); if t not in ('profiles','workspaces') then execute format('create index on public.%I(workspace_id)',t); end if; end loop; end $$;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from workspace_members m where m.user_id=profiles.id and is_member(m.workspace_id)));
create policy profile_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy workspace_read on public.workspaces for select to authenticated using(is_member(id));
create policy workspace_update on public.workspaces for update to authenticated using(is_admin(id)) with check(is_admin(id));
create policy member_read on public.workspace_members for select to authenticated using(is_member(workspace_id));
-- Membership changes go through dedicated Admin RPCs, never unrestricted table writes.
create policy project_read on public.projects for select to authenticated using(can_project(workspace_id,id));
create policy project_write on public.projects for all to authenticated using(is_manager(workspace_id)) with check(is_manager(workspace_id));
create policy project_member_read on public.project_members for select to authenticated using(can_project(workspace_id,project_id));
create policy project_member_write on public.project_members for all to authenticated using(is_manager(workspace_id)) with check(is_manager(workspace_id));
do $$ declare t text; begin foreach t in array array['clients','leads','estimates','estimate_items','invoices','invoice_items','payments'] loop execute format('create policy manager_access on public.%I for all to authenticated using (is_manager(workspace_id)) with check (is_manager(workspace_id))',t); end loop;
foreach t in array array['shoots','deliverables','tasks'] loop execute format('create policy project_read on public.%I for select to authenticated using (can_project(workspace_id,project_id))',t); execute format('create policy manager_write on public.%I for all to authenticated using (is_manager(workspace_id)) with check (is_manager(workspace_id))',t); end loop;
foreach t in array array['tasks','deliverables'] loop execute format('create policy assignee_update on public.%I for update to authenticated using (assignee_id=auth.uid() and can_project(workspace_id,project_id)) with check (assignee_id=auth.uid() and can_project(workspace_id,project_id))',t); end loop; end $$;
create policy activity_read on public.activity_logs for select to authenticated using(is_manager(workspace_id) or (project_id is not null and can_project(workspace_id,project_id)));
create function public.guard_editor() returns trigger language plpgsql as $$ begin if not is_manager(old.workspace_id) and (to_jsonb(new)-array['status','notes','delivery_url','revision_count','updated_at']) is distinct from (to_jsonb(old)-array['status','notes','delivery_url','revision_count','updated_at']) then raise exception 'Only progress updates are allowed'; end if; return new; end $$;
create trigger guard_editor before update on public.tasks for each row execute function public.guard_editor();
create trigger guard_editor before update on public.deliverables for each row execute function public.guard_editor();
create function public.log_activity() returns trigger language plpgsql security definer set search_path=public as $$ declare r jsonb; p uuid; begin r=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end; p=case when tg_table_name='projects' then (r->>'id')::uuid else (r->>'project_id')::uuid end; insert into activity_logs(workspace_id,project_id,entity,record_id,action,actor_id) values((r->>'workspace_id')::uuid,p,tg_table_name,(r->>'id')::uuid,lower(tg_op),auth.uid()); return coalesce(new,old); end $$;
do $$ declare t text; begin foreach t in array array['leads','clients','projects','shoots','tasks','deliverables','estimates','invoices','payments'] loop execute format('create trigger audit after insert or update or delete on public.%I for each row execute function public.log_activity()',t); end loop; end $$;
create function public.capture_delivery() returns trigger language plpgsql as $$ begin if new.status in ('Delivered','Completed') and new.delivered_at is null then new.delivered_at=now(); end if; return new; end $$;
create trigger capture_delivery before update on public.projects for each row execute function public.capture_delivery();
create index on public.tasks(workspace_id,assignee_id,due_date);
create index on public.deliverables(workspace_id,project_id,due_date);
create index on public.shoots(workspace_id,date);
create index on public.invoices(workspace_id,due_date);
create index on public.payments(invoice_id);
create index on public.project_members(user_id,project_id);

create function public.bootstrap_workspace(workspace_name text,full_name text) returns uuid language plpgsql security definer set search_path=public as $$ declare w uuid; begin
 if auth.uid() is null then raise exception 'Sign in required'; end if;
 if length(trim(workspace_name))<1 or length(workspace_name)>100 then raise exception 'Invalid name'; end if;
 perform pg_advisory_xact_lock(hashtext(auth.uid()::text));
 select workspace_id into w from workspace_members where user_id=auth.uid() limit 1;
 if w is not null then return w; end if;
 insert into profiles(id,name,email) values(auth.uid(),left(full_name,100),coalesce(auth.jwt()->>'email','')) on conflict(id) do nothing;
 insert into workspaces(name) values(workspace_name) returning id into w;
 insert into workspace_members(workspace_id,user_id,role) values(w,auth.uid(),'Admin'); return w; end $$;
create function public.join_member(w uuid,member_email text,member_role text) returns void language plpgsql security definer set search_path=public as $$ declare u uuid; begin
 if not is_admin(w) or member_role not in ('Admin','Manager','Editor') then raise exception 'Not allowed'; end if;
 select id into u from auth.users where lower(email)=lower(trim(member_email)); if u is null then raise exception 'User must sign up first'; end if;
 insert into profiles(id,email,name) values(u,member_email,split_part(member_email,'@',1)) on conflict(id) do nothing;
 insert into workspace_members(workspace_id,user_id,role) values(w,u,member_role) on conflict(workspace_id,user_id) do update set role=excluded.role;
 if not exists(select 1 from workspace_members where workspace_id=w and role='Admin') then raise exception 'Keep at least one admin'; end if;
 end $$;

-- Exact totals, matching the shared application calculation: fixed discount before tax,
-- proportionally allocated across rounded line subtotals, with tax rounded per line.
create function public.invoice_total(i uuid) returns numeric language sql stable security invoker set search_path=public as $$
 with lines as(select round(quantity*rate,2) s,tax from invoice_items where invoice_id=i), sub as(select coalesce(sum(s),0) s from lines), disc as(select least(v.discount,sub.s) d,sub.s from invoices v cross join sub where v.id=i)
 select coalesce((select s-d from disc),0)+coalesce((select sum(round(l.s*case when d.s=0 then 0 else (d.s-d.d)/d.s end*l.tax/100,2)) from lines l cross join disc d),0); $$;
create function public.guard_payment() returns trigger language plpgsql set search_path=public as $$ declare total numeric; paid numeric; st text; begin
 if tg_op<>'INSERT' then raise exception 'Payments are immutable'; end if;
 select status into st from invoices where id=new.invoice_id and workspace_id=new.workspace_id for update;
 if st is null or st<>'Sent' then raise exception 'Payments require a sent invoice'; end if;
 total=invoice_total(new.invoice_id); select coalesce(sum(amount),0) into paid from payments where invoice_id=new.invoice_id;
 if new.amount+paid>total then raise exception 'Payment exceeds balance'; end if; return new; end $$;
create trigger guard_payment before insert or update or delete on public.payments for each row execute function public.guard_payment();
create function public.guard_invoice() returns trigger language plpgsql set search_path=public as $$ begin
 if tg_op='DELETE' and old.status<>'Draft' then raise exception 'Only drafts can be deleted'; end if;
 if tg_op='UPDATE' and old.status<>'Draft' then
 if (to_jsonb(new)-array['status','updated_at']) is distinct from (to_jsonb(old)-array['status','updated_at']) or new.status not in ('Sent','Cancelled') or exists(select 1 from payments where invoice_id=old.id) then raise exception 'Issued invoice is locked'; end if;
 end if; return coalesce(new,old); end $$;
create trigger guard_invoice before update or delete on public.invoices for each row execute function public.guard_invoice();
create function public.guard_invoice_item() returns trigger language plpgsql set search_path=public as $$ declare p uuid; st text; begin p=case when tg_op='DELETE' then old.invoice_id else new.invoice_id end; select status into st from invoices where id=p for update; if st is distinct from 'Draft' then raise exception 'Issued invoice items are locked'; end if; if tg_op='UPDATE' and new.invoice_id<>old.invoice_id then raise exception 'Cannot move invoice items'; end if; return coalesce(new,old); end $$;
create trigger guard_invoice_item before insert or update or delete on public.invoice_items for each row execute function public.guard_invoice_item();
create function public.guard_invoice_client() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from projects where id=new.project_id and workspace_id=new.workspace_id and client_id=new.client_id) then raise exception 'Project and client must match'; end if; return new; end $$;
create trigger guard_invoice_client before insert or update on public.invoices for each row execute function public.guard_invoice_client();

create function public.save_document(kind text,w uuid,record_id uuid,payload jsonb) returns uuid language plpgsql security invoker set search_path=public as $$ declare rid uuid; item jsonb; begin
 if not is_manager(w) or kind not in ('estimates','invoices') then raise exception 'Not allowed'; end if;
 if jsonb_array_length(payload->'items')<1 then raise exception 'Add a service item'; end if;
 if kind='estimates' then
 if record_id is null then insert into estimates(workspace_id,name,client_id,lead_id,issue_date,valid_until,discount,notes,payment_terms,terms,status) values(w,payload->>'name',(payload->>'client_id')::uuid,(payload->>'lead_id')::uuid,(payload->>'issue_date')::date,(payload->>'valid_until')::date,coalesce((payload->>'discount')::numeric,0),payload->>'notes',payload->>'payment_terms',payload->>'terms',payload->>'status') returning id into rid;
 else update estimates set name=payload->>'name',client_id=(payload->>'client_id')::uuid,lead_id=(payload->>'lead_id')::uuid,issue_date=(payload->>'issue_date')::date,valid_until=(payload->>'valid_until')::date,discount=coalesce((payload->>'discount')::numeric,0),notes=payload->>'notes',payment_terms=payload->>'payment_terms',terms=payload->>'terms',status=payload->>'status' where id=record_id and workspace_id=w returning id into rid; end if;
 if rid is null then raise exception 'Record unavailable'; end if;
 delete from estimate_items where estimate_id=rid;
 for item in select * from jsonb_array_elements(payload->'items') loop insert into estimate_items(workspace_id,estimate_id,service,description,quantity,rate,tax) values(w,rid,item->>'service',item->>'description',(item->>'quantity')::numeric,(item->>'rate')::numeric,(item->>'tax')::numeric); end loop;
 else
 if record_id is null then insert into invoices(workspace_id,name,client_id,project_id,issue_date,due_date,discount,notes,payment_terms,status) values(w,payload->>'name',(payload->>'client_id')::uuid,(payload->>'project_id')::uuid,(payload->>'issue_date')::date,(payload->>'due_date')::date,coalesce((payload->>'discount')::numeric,0),payload->>'notes',payload->>'payment_terms','Draft') returning id into rid;
 else update invoices set name=payload->>'name',client_id=(payload->>'client_id')::uuid,project_id=(payload->>'project_id')::uuid,issue_date=(payload->>'issue_date')::date,due_date=(payload->>'due_date')::date,discount=coalesce((payload->>'discount')::numeric,0),notes=payload->>'notes',payment_terms=payload->>'payment_terms' where id=record_id and workspace_id=w returning id into rid; end if;
 if rid is null then raise exception 'Record unavailable'; end if;
 delete from invoice_items where invoice_id=rid;
 for item in select * from jsonb_array_elements(payload->'items') loop insert into invoice_items(workspace_id,invoice_id,service,description,quantity,rate,tax) values(w,rid,item->>'service',item->>'description',(item->>'quantity')::numeric,(item->>'rate')::numeric,(item->>'tax')::numeric); end loop;
 update invoices set status=payload->>'status' where id=rid;
 end if; return rid; end $$;
create function public.convert_estimate(estimate uuid) returns uuid language plpgsql security invoker set search_path=public as $$ declare e estimates; p uuid; begin
 select * into e from estimates where id=estimate for update;
 if e.id is null or not is_manager(e.workspace_id) or e.status<>'Accepted' then raise exception 'An accepted estimate is required'; end if;
 select id into p from projects where estimate_id=e.id;
 if p is null then insert into projects(workspace_id,name,client_id,estimate_id,brief,start_date) values(e.workspace_id,e.name,e.client_id,e.id,e.notes,current_date) returning id into p; end if; return p; end $$;
create function public.convert_lead(lead uuid,make_project boolean default false) returns jsonb language plpgsql security invoker set search_path=public as $$ declare l leads; c uuid; p uuid; begin
 select * into l from leads where id=lead for update; if l.id is null or not is_manager(l.workspace_id) then raise exception 'Not allowed'; end if;
 c=l.client_id; if c is null then insert into clients(workspace_id,name,contact,email,phone) values(l.workspace_id,coalesce(nullif(l.company,''),l.name),l.name,l.email,l.phone) returning id into c; update leads set client_id=c where id=l.id; end if;
 if make_project then if l.status<>'Won' then raise exception 'Mark this lead Won first'; end if;
 select id into p from projects where lead_id=l.id;
 if p is null then insert into projects(workspace_id,name,client_id,lead_id,brief,deadline) values(l.workspace_id,coalesce(l.service,l.name),c,l.id,l.notes,l.expected_date) returning id into p; end if; end if;
 return jsonb_build_object('client_id',c,'project_id',p); end $$;
revoke all on all functions in schema public from public;
grant execute on all functions in schema public to authenticated;
grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
